# Generated by Django 4.2.9 on 2024-01-10 15:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='contact_no',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(10)]),
        ),
        migrations.AddField(
            model_name='bloguser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
