# Generated by Django 4.2.9 on 2024-01-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_users', '0003_alter_bloguser_contact_no_alter_bloguser_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='contact_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
